<?php
/**
 * Countries.
 */
return [
    [
        'code' => 'ABW',
        'name' => 'Aruba',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 193,
        'population' => 103000,
        'gnp' => 828,
        'gnp_old' => 793,
        'local_name' => 'Aruba',
        'government_form' => 'Nonmetropolitan Territory of The Netherlands',
        'capital' => 129,
        'code2' => 'AW',
    ],
    [
        'code' => 'AFG',
        'name' => 'Afghanistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 652090,
        'population' => 22720000,
        'gnp' => 5976,
        'gnp_old' => null,
        'local_name' => 'Afganistan/Afqanestan',
        'government_form' => 'Islamic Emirate',
        'capital' => 1,
        'code2' => 'AF',
    ],
    [
        'code' => 'AGO',
        'name' => 'Angola',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 1246700,
        'population' => 12878000,
        'gnp' => 6648,
        'gnp_old' => 7984,
        'local_name' => 'Angola',
        'government_form' => 'Republic',
        'capital' => 56,
        'code2' => 'AO',
    ],
    [
        'code' => 'AIA',
        'name' => 'Anguilla',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 96,
        'population' => 8000,
        'gnp' => 63.200000000000003,
        'gnp_old' => null,
        'local_name' => 'Anguilla',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 62,
        'code2' => 'AI',
    ],
    [
        'code' => 'ALB',
        'name' => 'Albania',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 28748,
        'population' => 3401200,
        'gnp' => 3205,
        'gnp_old' => 2500,
        'local_name' => 'Shqipëria',
        'government_form' => 'Republic',
        'capital' => 34,
        'code2' => 'AL',
    ],
    [
        'code' => 'AND',
        'name' => 'Andorra',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 468,
        'population' => 78000,
        'gnp' => 1630,
        'gnp_old' => null,
        'local_name' => 'Andorra',
        'government_form' => 'Parliamentary Coprincipality',
        'capital' => 55,
        'code2' => 'AD',
    ],
    [
        'code' => 'ANT',
        'name' => 'Netherlands Antilles',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 800,
        'population' => 217000,
        'gnp' => 1941,
        'gnp_old' => null,
        'local_name' => 'Nederlandse Antillen',
        'government_form' => 'Nonmetropolitan Territory of The Netherlands',
        'capital' => 33,
        'code2' => 'AN',
    ],
    [
        'code' => 'ARE',
        'name' => 'United Arab Emirates',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 83600,
        'population' => 2441000,
        'gnp' => 37966,
        'gnp_old' => 36846,
        'local_name' => 'Al-Imarat al-´Arabiya al-Muttahida',
        'government_form' => 'Emirate Federation',
        'capital' => 65,
        'code2' => 'AE',
    ],
    [
        'code' => 'ARG',
        'name' => 'Argentina',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 2780400,
        'population' => 37032000,
        'gnp' => 340238,
        'gnp_old' => 323310,
        'local_name' => 'Argentina',
        'government_form' => 'Federal Republic',
        'capital' => 69,
        'code2' => 'AR',
    ],
    [
        'code' => 'ARM',
        'name' => 'Armenia',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 29800,
        'population' => 3520000,
        'gnp' => 1813,
        'gnp_old' => 1627,
        'local_name' => 'Hajastan',
        'government_form' => 'Republic',
        'capital' => 126,
        'code2' => 'AM',
    ],
    [
        'code' => 'ASM',
        'name' => 'American Samoa',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 199,
        'population' => 68000,
        'gnp' => 334,
        'gnp_old' => null,
        'local_name' => 'Amerika Samoa',
        'government_form' => 'US Territory',
        'capital' => 54,
        'code2' => 'AS',
    ],
    [
        'code' => 'ATA',
        'name' => 'Antarctica',
        'continent' => 'Antarctica',
        'region' => 'Antarctica',
        'surface_area' => 13120000,
        'population' => 0,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => '–',
        'government_form' => 'Co-administrated',
        'capital' => null,
        'code2' => 'AQ',
    ],
    [
        'code' => 'ATF',
        'name' => 'French Southern territories',
        'continent' => 'Antarctica',
        'region' => 'Antarctica',
        'surface_area' => 7780,
        'population' => 0,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Terres australes françaises',
        'government_form' => 'Nonmetropolitan Territory of France',
        'capital' => null,
        'code2' => 'TF',
    ],
    [
        'code' => 'ATG',
        'name' => 'Antigua and Barbuda',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 442,
        'population' => 68000,
        'gnp' => 612,
        'gnp_old' => 584,
        'local_name' => 'Antigua and Barbuda',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 63,
        'code2' => 'AG',
    ],
    [
        'code' => 'AUS',
        'name' => 'Australia',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'surface_area' => 7741220,
        'population' => 18886000,
        'gnp' => 351182,
        'gnp_old' => 392911,
        'local_name' => 'Australia',
        'government_form' => 'Constitutional Monarchy, Federation',
        'capital' => 135,
        'code2' => 'AU',
    ],
    [
        'code' => 'AUT',
        'name' => 'Austria',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 83859,
        'population' => 8091800,
        'gnp' => 211860,
        'gnp_old' => 206025,
        'local_name' => 'Österreich',
        'government_form' => 'Federal Republic',
        'capital' => 1523,
        'code2' => 'AT',
    ],
    [
        'code' => 'AZE',
        'name' => 'Azerbaijan',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 86600,
        'population' => 7734000,
        'gnp' => 4127,
        'gnp_old' => 4100,
        'local_name' => 'Azärbaycan',
        'government_form' => 'Federal Republic',
        'capital' => 144,
        'code2' => 'AZ',
    ],
    [
        'code' => 'BDI',
        'name' => 'Burundi',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 27834,
        'population' => 6695000,
        'gnp' => 903,
        'gnp_old' => 982,
        'local_name' => 'Burundi/Uburundi',
        'government_form' => 'Republic',
        'capital' => 552,
        'code2' => 'BI',
    ],
    [
        'code' => 'BEL',
        'name' => 'Belgium',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 30518,
        'population' => 10239000,
        'gnp' => 249704,
        'gnp_old' => 243948,
        'local_name' => 'België/Belgique',
        'government_form' => 'Constitutional Monarchy, Federation',
        'capital' => 179,
        'code2' => 'BE',
    ],
    [
        'code' => 'BEN',
        'name' => 'Benin',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 112622,
        'population' => 6097000,
        'gnp' => 2357,
        'gnp_old' => 2141,
        'local_name' => 'Bénin',
        'government_form' => 'Republic',
        'capital' => 187,
        'code2' => 'BJ',
    ],
    [
        'code' => 'BFA',
        'name' => 'Burkina Faso',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 274000,
        'population' => 11937000,
        'gnp' => 2425,
        'gnp_old' => 2201,
        'local_name' => 'Burkina Faso',
        'government_form' => 'Republic',
        'capital' => 549,
        'code2' => 'BF',
    ],
    [
        'code' => 'BGD',
        'name' => 'Bangladesh',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 143998,
        'population' => 129155000,
        'gnp' => 32852,
        'gnp_old' => 31966,
        'local_name' => 'Bangladesh',
        'government_form' => 'Republic',
        'capital' => 150,
        'code2' => 'BD',
    ],
    [
        'code' => 'BGR',
        'name' => 'Bulgaria',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 110994,
        'population' => 8190900,
        'gnp' => 12178,
        'gnp_old' => 10169,
        'local_name' => 'Balgarija',
        'government_form' => 'Republic',
        'capital' => 539,
        'code2' => 'BG',
    ],
    [
        'code' => 'BHR',
        'name' => 'Bahrain',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 694,
        'population' => 617000,
        'gnp' => 6366,
        'gnp_old' => 6097,
        'local_name' => 'Al-Bahrayn',
        'government_form' => 'Monarchy (Emirate)',
        'capital' => 149,
        'code2' => 'BH',
    ],
    [
        'code' => 'BHS',
        'name' => 'Bahamas',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 13878,
        'population' => 307000,
        'gnp' => 3527,
        'gnp_old' => 3347,
        'local_name' => 'The Bahamas',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 148,
        'code2' => 'BS',
    ],
    [
        'code' => 'BIH',
        'name' => 'Bosnia and Herzegovina',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 51197,
        'population' => 3972000,
        'gnp' => 2841,
        'gnp_old' => null,
        'local_name' => 'Bosna i Hercegovina',
        'government_form' => 'Federal Republic',
        'capital' => 201,
        'code2' => 'BA',
    ],
    [
        'code' => 'BLR',
        'name' => 'Belarus',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 207600,
        'population' => 10236000,
        'gnp' => 13714,
        'gnp_old' => null,
        'local_name' => 'Belarus',
        'government_form' => 'Republic',
        'capital' => 3520,
        'code2' => 'BY',
    ],
    [
        'code' => 'BLZ',
        'name' => 'Belize',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 22696,
        'population' => 241000,
        'gnp' => 630,
        'gnp_old' => 616,
        'local_name' => 'Belize',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 185,
        'code2' => 'BZ',
    ],
    [
        'code' => 'BMU',
        'name' => 'Bermuda',
        'continent' => 'North America',
        'region' => 'North America',
        'surface_area' => 53,
        'population' => 65000,
        'gnp' => 2328,
        'gnp_old' => 2190,
        'local_name' => 'Bermuda',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 191,
        'code2' => 'BM',
    ],
    [
        'code' => 'BOL',
        'name' => 'Bolivia',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 1098581,
        'population' => 8329000,
        'gnp' => 8571,
        'gnp_old' => 7967,
        'local_name' => 'Bolivia',
        'government_form' => 'Republic',
        'capital' => 194,
        'code2' => 'BO',
    ],
    [
        'code' => 'BRA',
        'name' => 'Brazil',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 8547403,
        'population' => 170115000,
        'gnp' => 776739,
        'gnp_old' => 804108,
        'local_name' => 'Brasil',
        'government_form' => 'Federal Republic',
        'capital' => 211,
        'code2' => 'BR',
    ],
    [
        'code' => 'BRB',
        'name' => 'Barbados',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 430,
        'population' => 270000,
        'gnp' => 2223,
        'gnp_old' => 2186,
        'local_name' => 'Barbados',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 174,
        'code2' => 'BB',
    ],
    [
        'code' => 'BRN',
        'name' => 'Brunei',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 5765,
        'population' => 328000,
        'gnp' => 11705,
        'gnp_old' => 12460,
        'local_name' => 'Brunei Darussalam',
        'government_form' => 'Monarchy (Sultanate)',
        'capital' => 538,
        'code2' => 'BN',
    ],
    [
        'code' => 'BTN',
        'name' => 'Bhutan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 47000,
        'population' => 2124000,
        'gnp' => 372,
        'gnp_old' => 383,
        'local_name' => 'Druk-Yul',
        'government_form' => 'Monarchy',
        'capital' => 192,
        'code2' => 'BT',
    ],
    [
        'code' => 'BVT',
        'name' => 'Bouvet Island',
        'continent' => 'Antarctica',
        'region' => 'Antarctica',
        'surface_area' => 59,
        'population' => 0,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Bouvetøya',
        'government_form' => 'Dependent Territory of Norway',
        'capital' => null,
        'code2' => 'BV',
    ],
    [
        'code' => 'BWA',
        'name' => 'Botswana',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'surface_area' => 581730,
        'population' => 1622000,
        'gnp' => 4834,
        'gnp_old' => 4935,
        'local_name' => 'Botswana',
        'government_form' => 'Republic',
        'capital' => 204,
        'code2' => 'BW',
    ],
    [
        'code' => 'CAF',
        'name' => 'Central African Republic',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 622984,
        'population' => 3615000,
        'gnp' => 1054,
        'gnp_old' => 993,
        'local_name' => 'Centrafrique/Bê-Afrîka',
        'government_form' => 'Republic',
        'capital' => 1889,
        'code2' => 'CF',
    ],
    [
        'code' => 'CAN',
        'name' => 'Canada',
        'continent' => 'North America',
        'region' => 'North America',
        'surface_area' => 9970610,
        'population' => 31147000,
        'gnp' => 598862,
        'gnp_old' => 625626,
        'local_name' => 'Canada',
        'government_form' => 'Constitutional Monarchy, Federation',
        'capital' => 1822,
        'code2' => 'CA',
    ],
    [
        'code' => 'CCK',
        'name' => 'Cocos (Keeling) Islands',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'surface_area' => 14,
        'population' => 600,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Cocos (Keeling) Islands',
        'government_form' => 'Territory of Australia',
        'capital' => 2317,
        'code2' => 'CC',
    ],
    [
        'code' => 'CHE',
        'name' => 'Switzerland',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 41284,
        'population' => 7160400,
        'gnp' => 264478,
        'gnp_old' => 256092,
        'local_name' => 'Schweiz/Suisse/Svizzera/Svizra',
        'government_form' => 'Federation',
        'capital' => 3248,
        'code2' => 'CH',
    ],
    [
        'code' => 'CHL',
        'name' => 'Chile',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 756626,
        'population' => 15211000,
        'gnp' => 72949,
        'gnp_old' => 75780,
        'local_name' => 'Chile',
        'government_form' => 'Republic',
        'capital' => 554,
        'code2' => 'CL',
    ],
    [
        'code' => 'CHN',
        'name' => 'China',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 9572900,
        'population' => 1277558000,
        'gnp' => 982268,
        'gnp_old' => 917719,
        'local_name' => 'Zhongquo',
        'government_form' => 'People\'sRepublic',
        'capital' => 1891,
        'code2' => 'CN',
    ],
    [
        'code' => 'CIV',
        'name' => 'Côte d’Ivoire',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 322463,
        'population' => 14786000,
        'gnp' => 11345,
        'gnp_old' => 10285,
        'local_name' => 'Côte d’Ivoire',
        'government_form' => 'Republic',
        'capital' => 2814,
        'code2' => 'CI',
    ],
    [
        'code' => 'CMR',
        'name' => 'Cameroon',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 475442,
        'population' => 15085000,
        'gnp' => 9174,
        'gnp_old' => 8596,
        'local_name' => 'Cameroun/Cameroon',
        'government_form' => 'Republic',
        'capital' => 1804,
        'code2' => 'CM',
    ],
    [
        'code' => 'COD',
        'name' => 'Congo, The Democratic Republic of the',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 2344858,
        'population' => 51654000,
        'gnp' => 6964,
        'gnp_old' => 2474,
        'local_name' => 'République Démocratique du Congo',
        'government_form' => 'Republic',
        'capital' => 2298,
        'code2' => 'CD',
    ],
    [
        'code' => 'COG',
        'name' => 'Congo',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 342000,
        'population' => 2943000,
        'gnp' => 2108,
        'gnp_old' => 2287,
        'local_name' => 'Congo',
        'government_form' => 'Republic',
        'capital' => 2296,
        'code2' => 'CG',
    ],
    [
        'code' => 'COK',
        'name' => 'Cook Islands',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 236,
        'population' => 20000,
        'gnp' => 100,
        'gnp_old' => null,
        'local_name' => 'The Cook Islands',
        'government_form' => 'Nonmetropolitan Territory of New Zealand',
        'capital' => 583,
        'code2' => 'CK',
    ],
    [
        'code' => 'COL',
        'name' => 'Colombia',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 1138914,
        'population' => 42321000,
        'gnp' => 102896,
        'gnp_old' => 105116,
        'local_name' => 'Colombia',
        'government_form' => 'Republic',
        'capital' => 2257,
        'code2' => 'CO',
    ],
    [
        'code' => 'COM',
        'name' => 'Comoros',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 1862,
        'population' => 578000,
        'gnp' => 4401,
        'gnp_old' => 4361,
        'local_name' => 'Komori/Comores',
        'government_form' => 'Republic',
        'capital' => 2295,
        'code2' => 'KM',
    ],
    [
        'code' => 'CPV',
        'name' => 'Cape Verde',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 4033,
        'population' => 428000,
        'gnp' => 435,
        'gnp_old' => 420,
        'local_name' => 'Cabo Verde',
        'government_form' => 'Republic',
        'capital' => 1859,
        'code2' => 'CV',
    ],
    [
        'code' => 'CRI',
        'name' => 'Costa Rica',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 51100,
        'population' => 4023000,
        'gnp' => 10226,
        'gnp_old' => 9757,
        'local_name' => 'Costa Rica',
        'government_form' => 'Republic',
        'capital' => 584,
        'code2' => 'CR',
    ],
    [
        'code' => 'CUB',
        'name' => 'Cuba',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 110861,
        'population' => 11201000,
        'gnp' => 17843,
        'gnp_old' => 18862,
        'local_name' => 'Cuba',
        'government_form' => 'Socialistic Republic',
        'capital' => 2413,
        'code2' => 'CU',
    ],
    [
        'code' => 'CXR',
        'name' => 'Christmas Island',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'surface_area' => 135,
        'population' => 2500,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Christmas Island',
        'government_form' => 'Territory of Australia',
        'capital' => 1791,
        'code2' => 'CX',
    ],
    [
        'code' => 'CYM',
        'name' => 'Cayman Islands',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 264,
        'population' => 38000,
        'gnp' => 1263,
        'gnp_old' => 1186,
        'local_name' => 'Cayman Islands',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 553,
        'code2' => 'KY',
    ],
    [
        'code' => 'CYP',
        'name' => 'Cyprus',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 9251,
        'population' => 754700,
        'gnp' => 9333,
        'gnp_old' => 8246,
        'local_name' => 'Kýpros/Kibris',
        'government_form' => 'Republic',
        'capital' => 2430,
        'code2' => 'CY',
    ],
    [
        'code' => 'CZE',
        'name' => 'Czech Republic',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 78866,
        'population' => 10278100,
        'gnp' => 55017,
        'gnp_old' => 52037,
        'local_name' => '¸esko',
        'government_form' => 'Republic',
        'capital' => 3339,
        'code2' => 'CZ',
    ],
    [
        'code' => 'DEU',
        'name' => 'Germany',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 357022,
        'population' => 82164700,
        'gnp' => 2133367,
        'gnp_old' => 2102826,
        'local_name' => 'Deutschland',
        'government_form' => 'Federal Republic',
        'capital' => 3068,
        'code2' => 'DE',
    ],
    [
        'code' => 'DJI',
        'name' => 'Djibouti',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 23200,
        'population' => 638000,
        'gnp' => 382,
        'gnp_old' => 373,
        'local_name' => 'Djibouti/Jibuti',
        'government_form' => 'Republic',
        'capital' => 585,
        'code2' => 'DJ',
    ],
    [
        'code' => 'DMA',
        'name' => 'Dominica',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 751,
        'population' => 71000,
        'gnp' => 256,
        'gnp_old' => 243,
        'local_name' => 'Dominica',
        'government_form' => 'Republic',
        'capital' => 586,
        'code2' => 'DM',
    ],
    [
        'code' => 'DNK',
        'name' => 'Denmark',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'surface_area' => 43094,
        'population' => 5330000,
        'gnp' => 174099,
        'gnp_old' => 169264,
        'local_name' => 'Danmark',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3315,
        'code2' => 'DK',
    ],
    [
        'code' => 'DOM',
        'name' => 'Dominican Republic',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 48511,
        'population' => 8495000,
        'gnp' => 15846,
        'gnp_old' => 15076,
        'local_name' => 'República Dominicana',
        'government_form' => 'Republic',
        'capital' => 587,
        'code2' => 'DO',
    ],
    [
        'code' => 'DZA',
        'name' => 'Algeria',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'surface_area' => 2381741,
        'population' => 31471000,
        'gnp' => 49982,
        'gnp_old' => 46966,
        'local_name' => 'Al-Jaza’ir/Algérie',
        'government_form' => 'Republic',
        'capital' => 35,
        'code2' => 'DZ',
    ],
    [
        'code' => 'ECU',
        'name' => 'Ecuador',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 283561,
        'population' => 12646000,
        'gnp' => 19770,
        'gnp_old' => 19769,
        'local_name' => 'Ecuador',
        'government_form' => 'Republic',
        'capital' => 594,
        'code2' => 'EC',
    ],
    [
        'code' => 'EGY',
        'name' => 'Egypt',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'surface_area' => 1001449,
        'population' => 68470000,
        'gnp' => 82710,
        'gnp_old' => 75617,
        'local_name' => 'Misr',
        'government_form' => 'Republic',
        'capital' => 608,
        'code2' => 'EG',
    ],
    [
        'code' => 'ERI',
        'name' => 'Eritrea',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 117600,
        'population' => 3850000,
        'gnp' => 650,
        'gnp_old' => 755,
        'local_name' => 'Ertra',
        'government_form' => 'Republic',
        'capital' => 652,
        'code2' => 'ER',
    ],
    [
        'code' => 'ESH',
        'name' => 'Western Sahara',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'surface_area' => 266000,
        'population' => 293000,
        'gnp' => 60,
        'gnp_old' => null,
        'local_name' => 'As-Sahrawiya',
        'government_form' => 'Occupied by Marocco',
        'capital' => 2453,
        'code2' => 'EH',
    ],
    [
        'code' => 'ESP',
        'name' => 'Spain',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 505992,
        'population' => 39441700,
        'gnp' => 553233,
        'gnp_old' => 532031,
        'local_name' => 'España',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 653,
        'code2' => 'ES',
    ],
    [
        'code' => 'EST',
        'name' => 'Estonia',
        'continent' => 'Europe',
        'region' => 'Baltic Countries',
        'surface_area' => 45227,
        'population' => 1439200,
        'gnp' => 5328,
        'gnp_old' => 3371,
        'local_name' => 'Eesti',
        'government_form' => 'Republic',
        'capital' => 3791,
        'code2' => 'EE',
    ],
    [
        'code' => 'ETH',
        'name' => 'Ethiopia',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 1104300,
        'population' => 62565000,
        'gnp' => 6353,
        'gnp_old' => 6180,
        'local_name' => 'YeItyop´iya',
        'government_form' => 'Republic',
        'capital' => 756,
        'code2' => 'ET',
    ],
    [
        'code' => 'FIN',
        'name' => 'Finland',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'surface_area' => 338145,
        'population' => 5171300,
        'gnp' => 121914,
        'gnp_old' => 119833,
        'local_name' => 'Suomi',
        'government_form' => 'Republic',
        'capital' => 3236,
        'code2' => 'FI',
    ],
    [
        'code' => 'FJI',
        'name' => 'Fiji Islands',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'surface_area' => 18274,
        'population' => 817000,
        'gnp' => 1536,
        'gnp_old' => 2149,
        'local_name' => 'Fiji Islands',
        'government_form' => 'Republic',
        'capital' => 764,
        'code2' => 'FJ',
    ],
    [
        'code' => 'FLK',
        'name' => 'Falkland Islands',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 12173,
        'population' => 2000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Falkland Islands',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 763,
        'code2' => 'FK',
    ],
    [
        'code' => 'FRA',
        'name' => 'France',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 551500,
        'population' => 59225700,
        'gnp' => 1424285,
        'gnp_old' => 1392448,
        'local_name' => 'France',
        'government_form' => 'Republic',
        'capital' => 2974,
        'code2' => 'FR',
    ],
    [
        'code' => 'FRO',
        'name' => 'Faroe Islands',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'surface_area' => 1399,
        'population' => 43000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Føroyar',
        'government_form' => 'Part of Denmark',
        'capital' => 901,
        'code2' => 'FO',
    ],
    [
        'code' => 'FSM',
        'name' => 'Micronesia, Federated States of',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'surface_area' => 702,
        'population' => 119000,
        'gnp' => 212,
        'gnp_old' => null,
        'local_name' => 'Micronesia',
        'government_form' => 'Federal Republic',
        'capital' => 2689,
        'code2' => 'FM',
    ],
    [
        'code' => 'GAB',
        'name' => 'Gabon',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 267668,
        'population' => 1226000,
        'gnp' => 5493,
        'gnp_old' => 5279,
        'local_name' => 'Le Gabon',
        'government_form' => 'Republic',
        'capital' => 902,
        'code2' => 'GA',
    ],
    [
        'code' => 'GBR',
        'name' => 'United Kingdom',
        'continent' => 'Europe',
        'region' => 'British Islands',
        'surface_area' => 242900,
        'population' => 59623400,
        'gnp' => 1378330,
        'gnp_old' => 1296830,
        'local_name' => 'United Kingdom',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 456,
        'code2' => 'GB',
    ],
    [
        'code' => 'GEO',
        'name' => 'Georgia',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 69700,
        'population' => 4968000,
        'gnp' => 6064,
        'gnp_old' => 5924,
        'local_name' => 'Sakartvelo',
        'government_form' => 'Republic',
        'capital' => 905,
        'code2' => 'GE',
    ],
    [
        'code' => 'GHA',
        'name' => 'Ghana',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 238533,
        'population' => 20212000,
        'gnp' => 7137,
        'gnp_old' => 6884,
        'local_name' => 'Ghana',
        'government_form' => 'Republic',
        'capital' => 910,
        'code2' => 'GH',
    ],
    [
        'code' => 'GIB',
        'name' => 'Gibraltar',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 6,
        'population' => 25000,
        'gnp' => 258,
        'gnp_old' => null,
        'local_name' => 'Gibraltar',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 915,
        'code2' => 'GI',
    ],
    [
        'code' => 'GIN',
        'name' => 'Guinea',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 245857,
        'population' => 7430000,
        'gnp' => 2352,
        'gnp_old' => 2383,
        'local_name' => 'Guinée',
        'government_form' => 'Republic',
        'capital' => 926,
        'code2' => 'GN',
    ],
    [
        'code' => 'GLP',
        'name' => 'Guadeloupe',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 1705,
        'population' => 456000,
        'gnp' => 3501,
        'gnp_old' => null,
        'local_name' => 'Guadeloupe',
        'government_form' => 'Overseas Department of France',
        'capital' => 919,
        'code2' => 'GP',
    ],
    [
        'code' => 'GMB',
        'name' => 'Gambia',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 11295,
        'population' => 1305000,
        'gnp' => 320,
        'gnp_old' => 325,
        'local_name' => 'The Gambia',
        'government_form' => 'Republic',
        'capital' => 904,
        'code2' => 'GM',
    ],
    [
        'code' => 'GNB',
        'name' => 'Guinea-Bissau',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 36125,
        'population' => 1213000,
        'gnp' => 293,
        'gnp_old' => 272,
        'local_name' => 'Guiné-Bissau',
        'government_form' => 'Republic',
        'capital' => 927,
        'code2' => 'GW',
    ],
    [
        'code' => 'GNQ',
        'name' => 'Equatorial Guinea',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 28051,
        'population' => 453000,
        'gnp' => 283,
        'gnp_old' => 542,
        'local_name' => 'Guinea Ecuatorial',
        'government_form' => 'Republic',
        'capital' => 2972,
        'code2' => 'GQ',
    ],
    [
        'code' => 'GRC',
        'name' => 'Greece',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 131626,
        'population' => 10545700,
        'gnp' => 120724,
        'gnp_old' => 119946,
        'local_name' => 'Elláda',
        'government_form' => 'Republic',
        'capital' => 2401,
        'code2' => 'GR',
    ],
    [
        'code' => 'GRD',
        'name' => 'Grenada',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 344,
        'population' => 94000,
        'gnp' => 318,
        'gnp_old' => null,
        'local_name' => 'Grenada',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 916,
        'code2' => 'GD',
    ],
    [
        'code' => 'GRL',
        'name' => 'Greenland',
        'continent' => 'North America',
        'region' => 'North America',
        'surface_area' => 2166090,
        'population' => 56000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Kalaallit Nunaat/Grønland',
        'government_form' => 'Part of Denmark',
        'capital' => 917,
        'code2' => 'GL',
    ],
    [
        'code' => 'GTM',
        'name' => 'Guatemala',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 108889,
        'population' => 11385000,
        'gnp' => 19008,
        'gnp_old' => 17797,
        'local_name' => 'Guatemala',
        'government_form' => 'Republic',
        'capital' => 922,
        'code2' => 'GT',
    ],
    [
        'code' => 'GUF',
        'name' => 'French Guiana',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 90000,
        'population' => 181000,
        'gnp' => 681,
        'gnp_old' => null,
        'local_name' => 'Guyane française',
        'government_form' => 'Overseas Department of France',
        'capital' => 3014,
        'code2' => 'GF',
    ],
    [
        'code' => 'GUM',
        'name' => 'Guam',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'surface_area' => 549,
        'population' => 168000,
        'gnp' => 1197,
        'gnp_old' => 1136,
        'local_name' => 'Guam',
        'government_form' => 'US Territory',
        'capital' => 921,
        'code2' => 'GU',
    ],
    [
        'code' => 'GUY',
        'name' => 'Guyana',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 214969,
        'population' => 861000,
        'gnp' => 722,
        'gnp_old' => 743,
        'local_name' => 'Guyana',
        'government_form' => 'Republic',
        'capital' => 928,
        'code2' => 'GY',
    ],
    [
        'code' => 'HKG',
        'name' => 'Hong Kong',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 1075,
        'population' => 6782000,
        'gnp' => 166448,
        'gnp_old' => 173610,
        'local_name' => 'Xianggang/Hong Kong',
        'government_form' => 'Special Administrative Region of China',
        'capital' => 937,
        'code2' => 'HK',
    ],
    [
        'code' => 'HMD',
        'name' => 'Heard Island and McDonald Islands',
        'continent' => 'Antarctica',
        'region' => 'Antarctica',
        'surface_area' => 359,
        'population' => 0,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Heard and McDonald Islands',
        'government_form' => 'Territory of Australia',
        'capital' => null,
        'code2' => 'HM',
    ],
    [
        'code' => 'HND',
        'name' => 'Honduras',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 112088,
        'population' => 6485000,
        'gnp' => 5333,
        'gnp_old' => 4697,
        'local_name' => 'Honduras',
        'government_form' => 'Republic',
        'capital' => 933,
        'code2' => 'HN',
    ],
    [
        'code' => 'HRV',
        'name' => 'Croatia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 56538,
        'population' => 4473000,
        'gnp' => 20208,
        'gnp_old' => 19300,
        'local_name' => 'Hrvatska',
        'government_form' => 'Republic',
        'capital' => 2409,
        'code2' => 'HR',
    ],
    [
        'code' => 'HTI',
        'name' => 'Haiti',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 27750,
        'population' => 8222000,
        'gnp' => 3459,
        'gnp_old' => 3107,
        'local_name' => 'Haïti/Dayti',
        'government_form' => 'Republic',
        'capital' => 929,
        'code2' => 'HT',
    ],
    [
        'code' => 'HUN',
        'name' => 'Hungary',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 93030,
        'population' => 10043200,
        'gnp' => 48267,
        'gnp_old' => 45914,
        'local_name' => 'Magyarország',
        'government_form' => 'Republic',
        'capital' => 3483,
        'code2' => 'HU',
    ],
    [
        'code' => 'IDN',
        'name' => 'Indonesia',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 1904569,
        'population' => 212107000,
        'gnp' => 84982,
        'gnp_old' => 215002,
        'local_name' => 'Indonesia',
        'government_form' => 'Republic',
        'capital' => 939,
        'code2' => 'ID',
    ],
    [
        'code' => 'IND',
        'name' => 'India',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 3287263,
        'population' => 1013662000,
        'gnp' => 447114,
        'gnp_old' => 430572,
        'local_name' => 'Bharat/India',
        'government_form' => 'Federal Republic',
        'capital' => 1109,
        'code2' => 'IN',
    ],
    [
        'code' => 'IOT',
        'name' => 'British Indian Ocean Territory',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 78,
        'population' => 0,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'British Indian Ocean Territory',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => null,
        'code2' => 'IO',
    ],
    [
        'code' => 'IRL',
        'name' => 'Ireland',
        'continent' => 'Europe',
        'region' => 'British Islands',
        'surface_area' => 70273,
        'population' => 3775100,
        'gnp' => 75921,
        'gnp_old' => 73132,
        'local_name' => 'Ireland/Éire',
        'government_form' => 'Republic',
        'capital' => 1447,
        'code2' => 'IE',
    ],
    [
        'code' => 'IRN',
        'name' => 'Iran',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 1648195,
        'population' => 67702000,
        'gnp' => 195746,
        'gnp_old' => 160151,
        'local_name' => 'Iran',
        'government_form' => 'Islamic Republic',
        'capital' => 1380,
        'code2' => 'IR',
    ],
    [
        'code' => 'IRQ',
        'name' => 'Iraq',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 438317,
        'population' => 23115000,
        'gnp' => 11500,
        'gnp_old' => null,
        'local_name' => 'Al-´Iraq',
        'government_form' => 'Republic',
        'capital' => 1365,
        'code2' => 'IQ',
    ],
    [
        'code' => 'ISL',
        'name' => 'Iceland',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'surface_area' => 103000,
        'population' => 279000,
        'gnp' => 8255,
        'gnp_old' => 7474,
        'local_name' => 'Ísland',
        'government_form' => 'Republic',
        'capital' => 1449,
        'code2' => 'IS',
    ],
    [
        'code' => 'ISR',
        'name' => 'Israel',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 21056,
        'population' => 6217000,
        'gnp' => 97477,
        'gnp_old' => 98577,
        'local_name' => 'Yisra’el/Isra’il',
        'government_form' => 'Republic',
        'capital' => 1450,
        'code2' => 'IL',
    ],
    [
        'code' => 'ITA',
        'name' => 'Italy',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 301316,
        'population' => 57680000,
        'gnp' => 1161755,
        'gnp_old' => 1145372,
        'local_name' => 'Italia',
        'government_form' => 'Republic',
        'capital' => 1464,
        'code2' => 'IT',
    ],
    [
        'code' => 'JAM',
        'name' => 'Jamaica',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 10990,
        'population' => 2583000,
        'gnp' => 6871,
        'gnp_old' => 6722,
        'local_name' => 'Jamaica',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 1530,
        'code2' => 'JM',
    ],
    [
        'code' => 'JOR',
        'name' => 'Jordan',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 88946,
        'population' => 5083000,
        'gnp' => 7526,
        'gnp_old' => 7051,
        'local_name' => 'Al-Urdunn',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 1786,
        'code2' => 'JO',
    ],
    [
        'code' => 'JPN',
        'name' => 'Japan',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 377829,
        'population' => 126714000,
        'gnp' => 3787042,
        'gnp_old' => 4192638,
        'local_name' => 'Nihon/Nippon',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 1532,
        'code2' => 'JP',
    ],
    [
        'code' => 'KAZ',
        'name' => 'Kazakstan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 2724900,
        'population' => 16223000,
        'gnp' => 24375,
        'gnp_old' => 23383,
        'local_name' => 'Qazaqstan',
        'government_form' => 'Republic',
        'capital' => 1864,
        'code2' => 'KZ',
    ],
    [
        'code' => 'KEN',
        'name' => 'Kenya',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 580367,
        'population' => 30080000,
        'gnp' => 9217,
        'gnp_old' => 10241,
        'local_name' => 'Kenya',
        'government_form' => 'Republic',
        'capital' => 1881,
        'code2' => 'KE',
    ],
    [
        'code' => 'KGZ',
        'name' => 'Kyrgyzstan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 199900,
        'population' => 4699000,
        'gnp' => 1626,
        'gnp_old' => 1767,
        'local_name' => 'Kyrgyzstan',
        'government_form' => 'Republic',
        'capital' => 2253,
        'code2' => 'KG',
    ],
    [
        'code' => 'KHM',
        'name' => 'Cambodia',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 181035,
        'population' => 11168000,
        'gnp' => 5121,
        'gnp_old' => 5670,
        'local_name' => 'Kâmpuchéa',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 1800,
        'code2' => 'KH',
    ],
    [
        'code' => 'KIR',
        'name' => 'Kiribati',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'surface_area' => 726,
        'population' => 83000,
        'gnp' => 40.700000000000003,
        'gnp_old' => null,
        'local_name' => 'Kiribati',
        'government_form' => 'Republic',
        'capital' => 2256,
        'code2' => 'KI',
    ],
    [
        'code' => 'KNA',
        'name' => 'Saint Kitts and Nevis',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 261,
        'population' => 38000,
        'gnp' => 299,
        'gnp_old' => null,
        'local_name' => 'Saint Kitts and Nevis',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3064,
        'code2' => 'KN',
    ],
    [
        'code' => 'KOR',
        'name' => 'South Korea',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 99434,
        'population' => 46844000,
        'gnp' => 320749,
        'gnp_old' => 442544,
        'local_name' => 'Taehan Min’guk (Namhan)',
        'government_form' => 'Republic',
        'capital' => 2331,
        'code2' => 'KR',
    ],
    [
        'code' => 'KWT',
        'name' => 'Kuwait',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 17818,
        'population' => 1972000,
        'gnp' => 27037,
        'gnp_old' => 30373,
        'local_name' => 'Al-Kuwayt',
        'government_form' => 'Constitutional Monarchy (Emirate)',
        'capital' => 2429,
        'code2' => 'KW',
    ],
    [
        'code' => 'LAO',
        'name' => 'Laos',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 236800,
        'population' => 5433000,
        'gnp' => 1292,
        'gnp_old' => 1746,
        'local_name' => 'Lao',
        'government_form' => 'Republic',
        'capital' => 2432,
        'code2' => 'LA',
    ],
    [
        'code' => 'LBN',
        'name' => 'Lebanon',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 10400,
        'population' => 3282000,
        'gnp' => 17121,
        'gnp_old' => 15129,
        'local_name' => 'Lubnan',
        'government_form' => 'Republic',
        'capital' => 2438,
        'code2' => 'LB',
    ],
    [
        'code' => 'LBR',
        'name' => 'Liberia',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 111369,
        'population' => 3154000,
        'gnp' => 2012,
        'gnp_old' => null,
        'local_name' => 'Liberia',
        'government_form' => 'Republic',
        'capital' => 2440,
        'code2' => 'LR',
    ],
    [
        'code' => 'LBY',
        'name' => 'Libyan Arab Jamahiriya',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'surface_area' => 1759540,
        'population' => 5605000,
        'gnp' => 44806,
        'gnp_old' => 40562,
        'local_name' => 'Libiya',
        'government_form' => 'Socialistic State',
        'capital' => 2441,
        'code2' => 'LY',
    ],
    [
        'code' => 'LCA',
        'name' => 'Saint Lucia',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 622,
        'population' => 154000,
        'gnp' => 571,
        'gnp_old' => null,
        'local_name' => 'Saint Lucia',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3065,
        'code2' => 'LC',
    ],
    [
        'code' => 'LIE',
        'name' => 'Liechtenstein',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 160,
        'population' => 32300,
        'gnp' => 1119,
        'gnp_old' => 1084,
        'local_name' => 'Liechtenstein',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2446,
        'code2' => 'LI',
    ],
    [
        'code' => 'LKA',
        'name' => 'Sri Lanka',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 65610,
        'population' => 18827000,
        'gnp' => 15706,
        'gnp_old' => 15091,
        'local_name' => 'Sri Lanka/Ilankai',
        'government_form' => 'Republic',
        'capital' => 3217,
        'code2' => 'LK',
    ],
    [
        'code' => 'LSO',
        'name' => 'Lesotho',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'surface_area' => 30355,
        'population' => 2153000,
        'gnp' => 1061,
        'gnp_old' => 1161,
        'local_name' => 'Lesotho',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2437,
        'code2' => 'LS',
    ],
    [
        'code' => 'LTU',
        'name' => 'Lithuania',
        'continent' => 'Europe',
        'region' => 'Baltic Countries',
        'surface_area' => 65301,
        'population' => 3698500,
        'gnp' => 10692,
        'gnp_old' => 9585,
        'local_name' => 'Lietuva',
        'government_form' => 'Republic',
        'capital' => 2447,
        'code2' => 'LT',
    ],
    [
        'code' => 'LUX',
        'name' => 'Luxembourg',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 2586,
        'population' => 435700,
        'gnp' => 16321,
        'gnp_old' => 15519,
        'local_name' => 'Luxembourg/Lëtzebuerg',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2452,
        'code2' => 'LU',
    ],
    [
        'code' => 'LVA',
        'name' => 'Latvia',
        'continent' => 'Europe',
        'region' => 'Baltic Countries',
        'surface_area' => 64589,
        'population' => 2424200,
        'gnp' => 6398,
        'gnp_old' => 5639,
        'local_name' => 'Latvija',
        'government_form' => 'Republic',
        'capital' => 2434,
        'code2' => 'LV',
    ],
    [
        'code' => 'MAC',
        'name' => 'Macao',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 18,
        'population' => 473000,
        'gnp' => 5749,
        'gnp_old' => 5940,
        'local_name' => 'Macau/Aomen',
        'government_form' => 'Special Administrative Region of China',
        'capital' => 2454,
        'code2' => 'MO',
    ],
    [
        'code' => 'MAR',
        'name' => 'Morocco',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'surface_area' => 446550,
        'population' => 28351000,
        'gnp' => 36124,
        'gnp_old' => 33514,
        'local_name' => 'Al-Maghrib',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2486,
        'code2' => 'MA',
    ],
    [
        'code' => 'MCO',
        'name' => 'Monaco',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 1.5,
        'population' => 34000,
        'gnp' => 776,
        'gnp_old' => null,
        'local_name' => 'Monaco',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2695,
        'code2' => 'MC',
    ],
    [
        'code' => 'MDA',
        'name' => 'Moldova',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 33851,
        'population' => 4380000,
        'gnp' => 1579,
        'gnp_old' => 1872,
        'local_name' => 'Moldova',
        'government_form' => 'Republic',
        'capital' => 2690,
        'code2' => 'MD',
    ],
    [
        'code' => 'MDG',
        'name' => 'Madagascar',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 587041,
        'population' => 15942000,
        'gnp' => 3750,
        'gnp_old' => 3545,
        'local_name' => 'Madagasikara/Madagascar',
        'government_form' => 'Federal Republic',
        'capital' => 2455,
        'code2' => 'MG',
    ],
    [
        'code' => 'MDV',
        'name' => 'Maldives',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 298,
        'population' => 286000,
        'gnp' => 199,
        'gnp_old' => null,
        'local_name' => 'Dhivehi Raajje/Maldives',
        'government_form' => 'Republic',
        'capital' => 2463,
        'code2' => 'MV',
    ],
    [
        'code' => 'MEX',
        'name' => 'Mexico',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 1958201,
        'population' => 98881000,
        'gnp' => 414972,
        'gnp_old' => 401461,
        'local_name' => 'México',
        'government_form' => 'Federal Republic',
        'capital' => 2515,
        'code2' => 'MX',
    ],
    [
        'code' => 'MHL',
        'name' => 'Marshall Islands',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'surface_area' => 181,
        'population' => 64000,
        'gnp' => 97,
        'gnp_old' => null,
        'local_name' => 'Marshall Islands/Majol',
        'government_form' => 'Republic',
        'capital' => 2507,
        'code2' => 'MH',
    ],
    [
        'code' => 'MKD',
        'name' => 'Macedonia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 25713,
        'population' => 2024000,
        'gnp' => 1694,
        'gnp_old' => 1915,
        'local_name' => 'Makedonija',
        'government_form' => 'Republic',
        'capital' => 2460,
        'code2' => 'MK',
    ],
    [
        'code' => 'MLI',
        'name' => 'Mali',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 1240192,
        'population' => 11234000,
        'gnp' => 2642,
        'gnp_old' => 2453,
        'local_name' => 'Mali',
        'government_form' => 'Republic',
        'capital' => 2482,
        'code2' => 'ML',
    ],
    [
        'code' => 'MLT',
        'name' => 'Malta',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 316,
        'population' => 380200,
        'gnp' => 3512,
        'gnp_old' => 3338,
        'local_name' => 'Malta',
        'government_form' => 'Republic',
        'capital' => 2484,
        'code2' => 'MT',
    ],
    [
        'code' => 'MMR',
        'name' => 'Myanmar',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 676578,
        'population' => 45611000,
        'gnp' => 180375,
        'gnp_old' => 171028,
        'local_name' => 'Myanma Pye',
        'government_form' => 'Republic',
        'capital' => 2710,
        'code2' => 'MM',
    ],
    [
        'code' => 'MNG',
        'name' => 'Mongolia',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 1566500,
        'population' => 2662000,
        'gnp' => 1043,
        'gnp_old' => 933,
        'local_name' => 'Mongol Uls',
        'government_form' => 'Republic',
        'capital' => 2696,
        'code2' => 'MN',
    ],
    [
        'code' => 'MNP',
        'name' => 'Northern Mariana Islands',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'surface_area' => 464,
        'population' => 78000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Northern Mariana Islands',
        'government_form' => 'Commonwealth of the US',
        'capital' => 2913,
        'code2' => 'MP',
    ],
    [
        'code' => 'MOZ',
        'name' => 'Mozambique',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 801590,
        'population' => 19680000,
        'gnp' => 2891,
        'gnp_old' => 2711,
        'local_name' => 'Moçambique',
        'government_form' => 'Republic',
        'capital' => 2698,
        'code2' => 'MZ',
    ],
    [
        'code' => 'MRT',
        'name' => 'Mauritania',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 1025520,
        'population' => 2670000,
        'gnp' => 998,
        'gnp_old' => 1081,
        'local_name' => 'Muritaniya/Mauritanie',
        'government_form' => 'Republic',
        'capital' => 2509,
        'code2' => 'MR',
    ],
    [
        'code' => 'MSR',
        'name' => 'Montserrat',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 102,
        'population' => 11000,
        'gnp' => 109,
        'gnp_old' => null,
        'local_name' => 'Montserrat',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 2697,
        'code2' => 'MS',
    ],
    [
        'code' => 'MTQ',
        'name' => 'Martinique',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 1102,
        'population' => 395000,
        'gnp' => 2731,
        'gnp_old' => 2559,
        'local_name' => 'Martinique',
        'government_form' => 'Overseas Department of France',
        'capital' => 2508,
        'code2' => 'MQ',
    ],
    [
        'code' => 'MUS',
        'name' => 'Mauritius',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 2040,
        'population' => 1158000,
        'gnp' => 4251,
        'gnp_old' => 4186,
        'local_name' => 'Mauritius',
        'government_form' => 'Republic',
        'capital' => 2511,
        'code2' => 'MU',
    ],
    [
        'code' => 'MWI',
        'name' => 'Malawi',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 118484,
        'population' => 10925000,
        'gnp' => 1687,
        'gnp_old' => 2527,
        'local_name' => 'Malawi',
        'government_form' => 'Republic',
        'capital' => 2462,
        'code2' => 'MW',
    ],
    [
        'code' => 'MYS',
        'name' => 'Malaysia',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 329758,
        'population' => 22244000,
        'gnp' => 69213,
        'gnp_old' => 97884,
        'local_name' => 'Malaysia',
        'government_form' => 'Constitutional Monarchy, Federation',
        'capital' => 2464,
        'code2' => 'MY',
    ],
    [
        'code' => 'MYT',
        'name' => 'Mayotte',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 373,
        'population' => 149000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Mayotte',
        'government_form' => 'Territorial Collectivity of France',
        'capital' => 2514,
        'code2' => 'YT',
    ],
    [
        'code' => 'NAM',
        'name' => 'Namibia',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'surface_area' => 824292,
        'population' => 1726000,
        'gnp' => 3101,
        'gnp_old' => 3384,
        'local_name' => 'Namibia',
        'government_form' => 'Republic',
        'capital' => 2726,
        'code2' => 'NA',
    ],
    [
        'code' => 'NCL',
        'name' => 'New Caledonia',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'surface_area' => 18575,
        'population' => 214000,
        'gnp' => 3563,
        'gnp_old' => null,
        'local_name' => 'Nouvelle-Calédonie',
        'government_form' => 'Nonmetropolitan Territory of France',
        'capital' => 3493,
        'code2' => 'NC',
    ],
    [
        'code' => 'NER',
        'name' => 'Niger',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 1267000,
        'population' => 10730000,
        'gnp' => 1706,
        'gnp_old' => 1580,
        'local_name' => 'Niger',
        'government_form' => 'Republic',
        'capital' => 2738,
        'code2' => 'NE',
    ],
    [
        'code' => 'NFK',
        'name' => 'Norfolk Island',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'surface_area' => 36,
        'population' => 2000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Norfolk Island',
        'government_form' => 'Territory of Australia',
        'capital' => 2806,
        'code2' => 'NF',
    ],
    [
        'code' => 'NGA',
        'name' => 'Nigeria',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 923768,
        'population' => 111506000,
        'gnp' => 65707,
        'gnp_old' => 58623,
        'local_name' => 'Nigeria',
        'government_form' => 'Federal Republic',
        'capital' => 2754,
        'code2' => 'NG',
    ],
    [
        'code' => 'NIC',
        'name' => 'Nicaragua',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 130000,
        'population' => 5074000,
        'gnp' => 1988,
        'gnp_old' => 2023,
        'local_name' => 'Nicaragua',
        'government_form' => 'Republic',
        'capital' => 2734,
        'code2' => 'NI',
    ],
    [
        'code' => 'NIU',
        'name' => 'Niue',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 260,
        'population' => 2000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Niue',
        'government_form' => 'Nonmetropolitan Territory of New Zealand',
        'capital' => 2805,
        'code2' => 'NU',
    ],
    [
        'code' => 'NLD',
        'name' => 'Netherlands',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'surface_area' => 41526,
        'population' => 15864000,
        'gnp' => 371362,
        'gnp_old' => 360478,
        'local_name' => 'Nederland',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 5,
        'code2' => 'NL',
    ],
    [
        'code' => 'NOR',
        'name' => 'Norway',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'surface_area' => 323877,
        'population' => 4478500,
        'gnp' => 145895,
        'gnp_old' => 153370,
        'local_name' => 'Norge',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2807,
        'code2' => 'NO',
    ],
    [
        'code' => 'NPL',
        'name' => 'Nepal',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 147181,
        'population' => 23930000,
        'gnp' => 4768,
        'gnp_old' => 4837,
        'local_name' => 'Nepal',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2729,
        'code2' => 'NP',
    ],
    [
        'code' => 'NRU',
        'name' => 'Nauru',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'surface_area' => 21,
        'population' => 12000,
        'gnp' => 197,
        'gnp_old' => null,
        'local_name' => 'Naoero/Nauru',
        'government_form' => 'Republic',
        'capital' => 2728,
        'code2' => 'NR',
    ],
    [
        'code' => 'NZL',
        'name' => 'New Zealand',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'surface_area' => 270534,
        'population' => 3862000,
        'gnp' => 54669,
        'gnp_old' => 64960,
        'local_name' => 'New Zealand/Aotearoa',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3499,
        'code2' => 'NZ',
    ],
    [
        'code' => 'OMN',
        'name' => 'Oman',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 309500,
        'population' => 2542000,
        'gnp' => 16904,
        'gnp_old' => 16153,
        'local_name' => '´Uman',
        'government_form' => 'Monarchy (Sultanate)',
        'capital' => 2821,
        'code2' => 'OM',
    ],
    [
        'code' => 'PAK',
        'name' => 'Pakistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 796095,
        'population' => 156483000,
        'gnp' => 61289,
        'gnp_old' => 58549,
        'local_name' => 'Pakistan',
        'government_form' => 'Republic',
        'capital' => 2831,
        'code2' => 'PK',
    ],
    [
        'code' => 'PAN',
        'name' => 'Panama',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 75517,
        'population' => 2856000,
        'gnp' => 9131,
        'gnp_old' => 8700,
        'local_name' => 'Panamá',
        'government_form' => 'Republic',
        'capital' => 2882,
        'code2' => 'PA',
    ],
    [
        'code' => 'PCN',
        'name' => 'Pitcairn',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 49,
        'population' => 50,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Pitcairn',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 2912,
        'code2' => 'PN',
    ],
    [
        'code' => 'PER',
        'name' => 'Peru',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 1285216,
        'population' => 25662000,
        'gnp' => 64140,
        'gnp_old' => 65186,
        'local_name' => 'Perú/Piruw',
        'government_form' => 'Republic',
        'capital' => 2890,
        'code2' => 'PE',
    ],
    [
        'code' => 'PHL',
        'name' => 'Philippines',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 300000,
        'population' => 75967000,
        'gnp' => 65107,
        'gnp_old' => 82239,
        'local_name' => 'Pilipinas',
        'government_form' => 'Republic',
        'capital' => 766,
        'code2' => 'PH',
    ],
    [
        'code' => 'PLW',
        'name' => 'Palau',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'surface_area' => 459,
        'population' => 19000,
        'gnp' => 105,
        'gnp_old' => null,
        'local_name' => 'Belau/Palau',
        'government_form' => 'Republic',
        'capital' => 2881,
        'code2' => 'PW',
    ],
    [
        'code' => 'PNG',
        'name' => 'Papua New Guinea',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'surface_area' => 462840,
        'population' => 4807000,
        'gnp' => 4988,
        'gnp_old' => 6328,
        'local_name' => 'Papua New Guinea/Papua Niugini',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 2884,
        'code2' => 'PG',
    ],
    [
        'code' => 'POL',
        'name' => 'Poland',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 323250,
        'population' => 38653600,
        'gnp' => 151697,
        'gnp_old' => 135636,
        'local_name' => 'Polska',
        'government_form' => 'Republic',
        'capital' => 2928,
        'code2' => 'PL',
    ],
    [
        'code' => 'PRI',
        'name' => 'Puerto Rico',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 8875,
        'population' => 3869000,
        'gnp' => 34100,
        'gnp_old' => 32100,
        'local_name' => 'Puerto Rico',
        'government_form' => 'Commonwealth of the US',
        'capital' => 2919,
        'code2' => 'PR',
    ],
    [
        'code' => 'PRK',
        'name' => 'North Korea',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 120538,
        'population' => 24039000,
        'gnp' => 5332,
        'gnp_old' => null,
        'local_name' => 'Choson Minjujuui In´min Konghwaguk (Bukhan)',
        'government_form' => 'Socialistic Republic',
        'capital' => 2318,
        'code2' => 'KP',
    ],
    [
        'code' => 'PRT',
        'name' => 'Portugal',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 91982,
        'population' => 9997600,
        'gnp' => 105954,
        'gnp_old' => 102133,
        'local_name' => 'Portugal',
        'government_form' => 'Republic',
        'capital' => 2914,
        'code2' => 'PT',
    ],
    [
        'code' => 'PRY',
        'name' => 'Paraguay',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 406752,
        'population' => 5496000,
        'gnp' => 8444,
        'gnp_old' => 9555,
        'local_name' => 'Paraguay',
        'government_form' => 'Republic',
        'capital' => 2885,
        'code2' => 'PY',
    ],
    [
        'code' => 'PSE',
        'name' => 'Palestine',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 6257,
        'population' => 3101000,
        'gnp' => 4173,
        'gnp_old' => null,
        'local_name' => 'Filastin',
        'government_form' => 'Autonomous Area',
        'capital' => 4074,
        'code2' => 'PS',
    ],
    [
        'code' => 'PYF',
        'name' => 'French Polynesia',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 4000,
        'population' => 235000,
        'gnp' => 818,
        'gnp_old' => 781,
        'local_name' => 'Polynésie française',
        'government_form' => 'Nonmetropolitan Territory of France',
        'capital' => 3016,
        'code2' => 'PF',
    ],
    [
        'code' => 'QAT',
        'name' => 'Qatar',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 11000,
        'population' => 599000,
        'gnp' => 9472,
        'gnp_old' => 8920,
        'local_name' => 'Qatar',
        'government_form' => 'Monarchy',
        'capital' => 2973,
        'code2' => 'QA',
    ],
    [
        'code' => 'REU',
        'name' => 'Réunion',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 2510,
        'population' => 699000,
        'gnp' => 8287,
        'gnp_old' => 7988,
        'local_name' => 'Réunion',
        'government_form' => 'Overseas Department of France',
        'capital' => 3017,
        'code2' => 'RE',
    ],
    [
        'code' => 'ROM',
        'name' => 'Romania',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 238391,
        'population' => 22455500,
        'gnp' => 38158,
        'gnp_old' => 34843,
        'local_name' => 'România',
        'government_form' => 'Republic',
        'capital' => 3018,
        'code2' => 'RO',
    ],
    [
        'code' => 'RUS',
        'name' => 'Russian Federation',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 17075400,
        'population' => 146934000,
        'gnp' => 276608,
        'gnp_old' => 442989,
        'local_name' => 'Rossija',
        'government_form' => 'Federal Republic',
        'capital' => 3580,
        'code2' => 'RU',
    ],
    [
        'code' => 'RWA',
        'name' => 'Rwanda',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 26338,
        'population' => 7733000,
        'gnp' => 2036,
        'gnp_old' => 1863,
        'local_name' => 'Rwanda/Urwanda',
        'government_form' => 'Republic',
        'capital' => 3047,
        'code2' => 'RW',
    ],
    [
        'code' => 'SAU',
        'name' => 'Saudi Arabia',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 2149690,
        'population' => 21607000,
        'gnp' => 137635,
        'gnp_old' => 146171,
        'local_name' => 'Al-´Arabiya as-Sa´udiya',
        'government_form' => 'Monarchy',
        'capital' => 3173,
        'code2' => 'SA',
    ],
    [
        'code' => 'SDN',
        'name' => 'Sudan',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'surface_area' => 2505813,
        'population' => 29490000,
        'gnp' => 10162,
        'gnp_old' => null,
        'local_name' => 'As-Sudan',
        'government_form' => 'Islamic Republic',
        'capital' => 3225,
        'code2' => 'SD',
    ],
    [
        'code' => 'SEN',
        'name' => 'Senegal',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 196722,
        'population' => 9481000,
        'gnp' => 4787,
        'gnp_old' => 4542,
        'local_name' => 'Sénégal/Sounougal',
        'government_form' => 'Republic',
        'capital' => 3198,
        'code2' => 'SN',
    ],
    [
        'code' => 'SGP',
        'name' => 'Singapore',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 618,
        'population' => 3567000,
        'gnp' => 86503,
        'gnp_old' => 96318,
        'local_name' => 'Singapore/Singapura/Xinjiapo/Singapur',
        'government_form' => 'Republic',
        'capital' => 3208,
        'code2' => 'SG',
    ],
    [
        'code' => 'SGS',
        'name' => 'South Georgia and the South Sandwich Islands',
        'continent' => 'Antarctica',
        'region' => 'Antarctica',
        'surface_area' => 3903,
        'population' => 0,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'South Georgia and the South Sandwich Islands',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => null,
        'code2' => 'GS',
    ],
    [
        'code' => 'SHN',
        'name' => 'Saint Helena',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 314,
        'population' => 6000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Saint Helena',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 3063,
        'code2' => 'SH',
    ],
    [
        'code' => 'SJM',
        'name' => 'Svalbard and Jan Mayen',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'surface_area' => 62422,
        'population' => 3200,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Svalbard og Jan Mayen',
        'government_form' => 'Dependent Territory of Norway',
        'capital' => 938,
        'code2' => 'SJ',
    ],
    [
        'code' => 'SLB',
        'name' => 'Solomon Islands',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'surface_area' => 28896,
        'population' => 444000,
        'gnp' => 182,
        'gnp_old' => 220,
        'local_name' => 'Solomon Islands',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3161,
        'code2' => 'SB',
    ],
    [
        'code' => 'SLE',
        'name' => 'Sierra Leone',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 71740,
        'population' => 4854000,
        'gnp' => 746,
        'gnp_old' => 858,
        'local_name' => 'Sierra Leone',
        'government_form' => 'Republic',
        'capital' => 3207,
        'code2' => 'SL',
    ],
    [
        'code' => 'SLV',
        'name' => 'El Salvador',
        'continent' => 'North America',
        'region' => 'Central America',
        'surface_area' => 21041,
        'population' => 6276000,
        'gnp' => 11863,
        'gnp_old' => 11203,
        'local_name' => 'El Salvador',
        'government_form' => 'Republic',
        'capital' => 645,
        'code2' => 'SV',
    ],
    [
        'code' => 'SMR',
        'name' => 'San Marino',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 61,
        'population' => 27000,
        'gnp' => 510,
        'gnp_old' => null,
        'local_name' => 'San Marino',
        'government_form' => 'Republic',
        'capital' => 3171,
        'code2' => 'SM',
    ],
    [
        'code' => 'SOM',
        'name' => 'Somalia',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 637657,
        'population' => 10097000,
        'gnp' => 935,
        'gnp_old' => null,
        'local_name' => 'Soomaaliya',
        'government_form' => 'Republic',
        'capital' => 3214,
        'code2' => 'SO',
    ],
    [
        'code' => 'SPM',
        'name' => 'Saint Pierre and Miquelon',
        'continent' => 'North America',
        'region' => 'North America',
        'surface_area' => 242,
        'population' => 7000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Saint-Pierre-et-Miquelon',
        'government_form' => 'Territorial Collectivity of France',
        'capital' => 3067,
        'code2' => 'PM',
    ],
    [
        'code' => 'STP',
        'name' => 'Sao Tome and Principe',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 964,
        'population' => 147000,
        'gnp' => 6,
        'gnp_old' => null,
        'local_name' => 'São Tomé e Príncipe',
        'government_form' => 'Republic',
        'capital' => 3172,
        'code2' => 'ST',
    ],
    [
        'code' => 'SUR',
        'name' => 'Suriname',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 163265,
        'population' => 417000,
        'gnp' => 870,
        'gnp_old' => 706,
        'local_name' => 'Suriname',
        'government_form' => 'Republic',
        'capital' => 3243,
        'code2' => 'SR',
    ],
    [
        'code' => 'SVK',
        'name' => 'Slovakia',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 49012,
        'population' => 5398700,
        'gnp' => 20594,
        'gnp_old' => 19452,
        'local_name' => 'Slovensko',
        'government_form' => 'Republic',
        'capital' => 3209,
        'code2' => 'SK',
    ],
    [
        'code' => 'SVN',
        'name' => 'Slovenia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 20256,
        'population' => 1987800,
        'gnp' => 19756,
        'gnp_old' => 18202,
        'local_name' => 'Slovenija',
        'government_form' => 'Republic',
        'capital' => 3212,
        'code2' => 'SI',
    ],
    [
        'code' => 'SWE',
        'name' => 'Sweden',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'surface_area' => 449964,
        'population' => 8861400,
        'gnp' => 226492,
        'gnp_old' => 227757,
        'local_name' => 'Sverige',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3048,
        'code2' => 'SE',
    ],
    [
        'code' => 'SWZ',
        'name' => 'Swaziland',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'surface_area' => 17364,
        'population' => 1008000,
        'gnp' => 1206,
        'gnp_old' => 1312,
        'local_name' => 'kaNgwane',
        'government_form' => 'Monarchy',
        'capital' => 3244,
        'code2' => 'SZ',
    ],
    [
        'code' => 'SYC',
        'name' => 'Seychelles',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 455,
        'population' => 77000,
        'gnp' => 536,
        'gnp_old' => 539,
        'local_name' => 'Sesel/Seychelles',
        'government_form' => 'Republic',
        'capital' => 3206,
        'code2' => 'SC',
    ],
    [
        'code' => 'SYR',
        'name' => 'Syria',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 185180,
        'population' => 16125000,
        'gnp' => 65984,
        'gnp_old' => 64926,
        'local_name' => 'Suriya',
        'government_form' => 'Republic',
        'capital' => 3250,
        'code2' => 'SY',
    ],
    [
        'code' => 'TCA',
        'name' => 'Turks and Caicos Islands',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 430,
        'population' => 17000,
        'gnp' => 96,
        'gnp_old' => null,
        'local_name' => 'The Turks and Caicos Islands',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 3423,
        'code2' => 'TC',
    ],
    [
        'code' => 'TCD',
        'name' => 'Chad',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'surface_area' => 1284000,
        'population' => 7651000,
        'gnp' => 1208,
        'gnp_old' => 1102,
        'local_name' => 'Tchad/Tshad',
        'government_form' => 'Republic',
        'capital' => 3337,
        'code2' => 'TD',
    ],
    [
        'code' => 'TGO',
        'name' => 'Togo',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'surface_area' => 56785,
        'population' => 4629000,
        'gnp' => 1449,
        'gnp_old' => 1400,
        'local_name' => 'Togo',
        'government_form' => 'Republic',
        'capital' => 3332,
        'code2' => 'TG',
    ],
    [
        'code' => 'THA',
        'name' => 'Thailand',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 513115,
        'population' => 61399000,
        'gnp' => 116416,
        'gnp_old' => 153907,
        'local_name' => 'Prathet Thai',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3320,
        'code2' => 'TH',
    ],
    [
        'code' => 'TJK',
        'name' => 'Tajikistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 143100,
        'population' => 6188000,
        'gnp' => 1990,
        'gnp_old' => 1056,
        'local_name' => 'Toçikiston',
        'government_form' => 'Republic',
        'capital' => 3261,
        'code2' => 'TJ',
    ],
    [
        'code' => 'TKL',
        'name' => 'Tokelau',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 12,
        'population' => 2000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Tokelau',
        'government_form' => 'Nonmetropolitan Territory of New Zealand',
        'capital' => 3333,
        'code2' => 'TK',
    ],
    [
        'code' => 'TKM',
        'name' => 'Turkmenistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 488100,
        'population' => 4459000,
        'gnp' => 4397,
        'gnp_old' => 2000,
        'local_name' => 'Türkmenostan',
        'government_form' => 'Republic',
        'capital' => 3419,
        'code2' => 'TM',
    ],
    [
        'code' => 'TMP',
        'name' => 'East Timor',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 14874,
        'population' => 885000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Timor Timur',
        'government_form' => 'Administrated by the UN',
        'capital' => 1522,
        'code2' => 'TP',
    ],
    [
        'code' => 'TON',
        'name' => 'Tonga',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 650,
        'population' => 99000,
        'gnp' => 146,
        'gnp_old' => 170,
        'local_name' => 'Tonga',
        'government_form' => 'Monarchy',
        'capital' => 3334,
        'code2' => 'TO',
    ],
    [
        'code' => 'TTO',
        'name' => 'Trinidad and Tobago',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 5130,
        'population' => 1295000,
        'gnp' => 6232,
        'gnp_old' => 5867,
        'local_name' => 'Trinidad and Tobago',
        'government_form' => 'Republic',
        'capital' => 3336,
        'code2' => 'TT',
    ],
    [
        'code' => 'TUN',
        'name' => 'Tunisia',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'surface_area' => 163610,
        'population' => 9586000,
        'gnp' => 20026,
        'gnp_old' => 18898,
        'local_name' => 'Tunis/Tunisie',
        'government_form' => 'Republic',
        'capital' => 3349,
        'code2' => 'TN',
    ],
    [
        'code' => 'TUR',
        'name' => 'Turkey',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 774815,
        'population' => 66591000,
        'gnp' => 210721,
        'gnp_old' => 189122,
        'local_name' => 'Türkiye',
        'government_form' => 'Republic',
        'capital' => 3358,
        'code2' => 'TR',
    ],
    [
        'code' => 'TUV',
        'name' => 'Tuvalu',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 26,
        'population' => 12000,
        'gnp' => 6,
        'gnp_old' => null,
        'local_name' => 'Tuvalu',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3424,
        'code2' => 'TV',
    ],
    [
        'code' => 'TWN',
        'name' => 'Taiwan',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'surface_area' => 36188,
        'population' => 22256000,
        'gnp' => 256254,
        'gnp_old' => 263451,
        'local_name' => 'T’ai-wan',
        'government_form' => 'Republic',
        'capital' => 3263,
        'code2' => 'TW',
    ],
    [
        'code' => 'TZA',
        'name' => 'Tanzania',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 883749,
        'population' => 33517000,
        'gnp' => 8005,
        'gnp_old' => 7388,
        'local_name' => 'Tanzania',
        'government_form' => 'Republic',
        'capital' => 3306,
        'code2' => 'TZ',
    ],
    [
        'code' => 'UGA',
        'name' => 'Uganda',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 241038,
        'population' => 21778000,
        'gnp' => 6313,
        'gnp_old' => 6887,
        'local_name' => 'Uganda',
        'government_form' => 'Republic',
        'capital' => 3425,
        'code2' => 'UG',
    ],
    [
        'code' => 'UKR',
        'name' => 'Ukraine',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'surface_area' => 603700,
        'population' => 50456000,
        'gnp' => 42168,
        'gnp_old' => 49677,
        'local_name' => 'Ukrajina',
        'government_form' => 'Republic',
        'capital' => 3426,
        'code2' => 'UA',
    ],
    [
        'code' => 'UMI',
        'name' => 'United States Minor Outlying Islands',
        'continent' => 'Oceania',
        'region' => 'Micronesia/Caribbean',
        'surface_area' => 16,
        'population' => 0,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'United States Minor Outlying Islands',
        'government_form' => 'Dependent Territory of the US',
        'capital' => null,
        'code2' => 'UM',
    ],
    [
        'code' => 'URY',
        'name' => 'Uruguay',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 175016,
        'population' => 3337000,
        'gnp' => 20831,
        'gnp_old' => 19967,
        'local_name' => 'Uruguay',
        'government_form' => 'Republic',
        'capital' => 3492,
        'code2' => 'UY',
    ],
    [
        'code' => 'USA',
        'name' => 'United States',
        'continent' => 'North America',
        'region' => 'North America',
        'surface_area' => 9363520,
        'population' => 278357000,
        'gnp' => 8510700,
        'gnp_old' => 8110900,
        'local_name' => 'United States',
        'government_form' => 'Federal Republic',
        'capital' => 3813,
        'code2' => 'US',
    ],
    [
        'code' => 'UZB',
        'name' => 'Uzbekistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'surface_area' => 447400,
        'population' => 24318000,
        'gnp' => 14194,
        'gnp_old' => 21300,
        'local_name' => 'Uzbekiston',
        'government_form' => 'Republic',
        'capital' => 3503,
        'code2' => 'UZ',
    ],
    [
        'code' => 'VAT',
        'name' => 'Holy See (Vatican City State)',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 0.40000000000000002,
        'population' => 1000,
        'gnp' => 9,
        'gnp_old' => null,
        'local_name' => 'Santa Sede/Città del Vaticano',
        'government_form' => 'Independent Church State',
        'capital' => 3538,
        'code2' => 'VA',
    ],
    [
        'code' => 'VCT',
        'name' => 'Saint Vincent and the Grenadines',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 388,
        'population' => 114000,
        'gnp' => 285,
        'gnp_old' => null,
        'local_name' => 'Saint Vincent and the Grenadines',
        'government_form' => 'Constitutional Monarchy',
        'capital' => 3066,
        'code2' => 'VC',
    ],
    [
        'code' => 'VEN',
        'name' => 'Venezuela',
        'continent' => 'South America',
        'region' => 'South America',
        'surface_area' => 912050,
        'population' => 24170000,
        'gnp' => 95023,
        'gnp_old' => 88434,
        'local_name' => 'Venezuela',
        'government_form' => 'Federal Republic',
        'capital' => 3539,
        'code2' => 'VE',
    ],
    [
        'code' => 'VGB',
        'name' => 'Virgin Islands, British',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 151,
        'population' => 21000,
        'gnp' => 612,
        'gnp_old' => 573,
        'local_name' => 'British Virgin Islands',
        'government_form' => 'Dependent Territory of the UK',
        'capital' => 537,
        'code2' => 'VG',
    ],
    [
        'code' => 'VIR',
        'name' => 'Virgin Islands, U.S.',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'surface_area' => 347,
        'population' => 93000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Virgin Islands of the United States',
        'government_form' => 'US Territory',
        'capital' => 4067,
        'code2' => 'VI',
    ],
    [
        'code' => 'VNM',
        'name' => 'Vietnam',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'surface_area' => 331689,
        'population' => 79832000,
        'gnp' => 21929,
        'gnp_old' => 22834,
        'local_name' => 'Viêt Nam',
        'government_form' => 'Socialistic Republic',
        'capital' => 3770,
        'code2' => 'VN',
    ],
    [
        'code' => 'VUT',
        'name' => 'Vanuatu',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'surface_area' => 12189,
        'population' => 190000,
        'gnp' => 261,
        'gnp_old' => 246,
        'local_name' => 'Vanuatu',
        'government_form' => 'Republic',
        'capital' => 3537,
        'code2' => 'VU',
    ],
    [
        'code' => 'WLF',
        'name' => 'Wallis and Futuna',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 200,
        'population' => 15000,
        'gnp' => 0,
        'gnp_old' => null,
        'local_name' => 'Wallis-et-Futuna',
        'government_form' => 'Nonmetropolitan Territory of France',
        'capital' => 3536,
        'code2' => 'WF',
    ],
    [
        'code' => 'WSM',
        'name' => 'Samoa',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'surface_area' => 2831,
        'population' => 180000,
        'gnp' => 141,
        'gnp_old' => 157,
        'local_name' => 'Samoa',
        'government_form' => 'Parlementary Monarchy',
        'capital' => 3169,
        'code2' => 'WS',
    ],
    [
        'code' => 'YEM',
        'name' => 'Yemen',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'surface_area' => 527968,
        'population' => 18112000,
        'gnp' => 6041,
        'gnp_old' => 5729,
        'local_name' => 'Al-Yaman',
        'government_form' => 'Republic',
        'capital' => 1780,
        'code2' => 'YE',
    ],
    [
        'code' => 'YUG',
        'name' => 'Yugoslavia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'surface_area' => 102173,
        'population' => 10640000,
        'gnp' => 17000,
        'gnp_old' => null,
        'local_name' => 'Jugoslavija',
        'government_form' => 'Federal Republic',
        'capital' => 1792,
        'code2' => 'YU',
    ],
    [
        'code' => 'ZAF',
        'name' => 'South Africa',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'surface_area' => 1221037,
        'population' => 40377000,
        'gnp' => 116729,
        'gnp_old' => 129092,
        'local_name' => 'South Africa',
        'government_form' => 'Republic',
        'capital' => 716,
        'code2' => 'ZA',
    ],
    [
        'code' => 'ZMB',
        'name' => 'Zambia',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 752618,
        'population' => 9169000,
        'gnp' => 3377,
        'gnp_old' => 3922,
        'local_name' => 'Zambia',
        'government_form' => 'Republic',
        'capital' => 3162,
        'code2' => 'ZM',
    ],
    [
        'code' => 'ZWE',
        'name' => 'Zimbabwe',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'surface_area' => 390757,
        'population' => 11669000,
        'gnp' => 5951,
        'gnp_old' => 8670,
        'local_name' => 'Zimbabwe',
        'government_form' => 'Republic',
        'capital' => 4068,
        'code2' => 'ZW',
    ],
];
